"""Add CalorieEntry table

Revision ID: 243876011669
Revises: b1d700d57227
Create Date: 2024-12-03 15:40:57.647525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243876011669'
down_revision = 'b1d700d57227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calorie_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calorie_entry')
    # ### end Alembic commands ###
